In [2]:
import pandas as pd
import numpy as np

import folium
from folium.plugins import HeatMap

import countries

In [3]:
rd = pd.read_csv("./Ready_Data.csv", encoding = "utf-8")
rd.head()

,Unnamed: 0,Unnamed: 0.1,ID,Name,Created_at,Location,Lat,Long,Text,Sentiment,Toxic,severe_toxicity,Obscene,Threat,Insult,identity_attack,sexual_explicit
0,0,0,1.237220e+18,lorihlewis54,3/10/2020 3:38,"Atlanta, GA.",-85.154953,32.970746,Hail to the Yam In Command!\n#YamInCommand\n#c...,0.981934,0.011158,0.000925,0.002397,0.001957,0.007177,0.002217,0.001325
1,1,1,1.237220e+18,jlay02,3/10/2020 3:38,Vaughan SS,-79.639319,43.403221,Wuhan students tried to boot remote learning a...,0.545410,0.011201,0.000833,0.001832,0.002332,0.006798,0.001803,0.001320
2,2,2,1.237220e+18,candacegranberg,3/10/2020 3:38,NaN,-97.239256,43.499362,How it is going down in Italy...\n#COVID���19 ...,0.074097,0.005865,0.000662,0.001284,0.001727,0.002758,0.001761,0.001240
3,3,3,1.237220e+18,david_whittier,3/10/2020 3:38,"Palm Springs, CA",-116.567788,33.779426,The scary part.... I could see @realDonaldTrum...,0.133301,0.804406,0.021781,0.137185,0.003390,0.787441,0.006931,0.002591
4,4,4,1.237220e+18,intensoblade,3/10/2020 3:37,"T��gerig, Switzerland",7.994212,47.360409,"@IngrahamAngle Hey, #NotSoSweetyPieLauraIngrah...",0.928223,0.330147,0.034815,0.009020,0.246533,0.059976,0.076961,0.001761

In [4]:
data = pd.DataFrame(rd, columns = ['Created_at', 'Long', 'Lat', 'Sentiment', 
                                'Toxic', 'severe_toxicity', 'Obscene', 'Threat', 
                                'Insult', 'identity_attack', 'sexual_explicit'])
data = data.rename(columns = {'Long': 'lat', 'Lat': 'lon'})
data.head()

,Created_at,lat,lon,Sentiment,Toxic,severe_toxicity,Obscene,Threat,Insult,identity_attack,sexual_explicit
0,3/10/2020 3:38,32.970746,-85.154953,0.981934,0.011158,0.000925,0.002397,0.001957,0.007177,0.002217,0.001325
1,3/10/2020 3:38,43.403221,-79.639319,0.545410,0.011201,0.000833,0.001832,0.002332,0.006798,0.001803,0.001320
2,3/10/2020 3:38,43.499362,-97.239256,0.074097,0.005865,0.000662,0.001284,0.001727,0.002758,0.001761,0.001240
3,3/10/2020 3:38,33.779426,-116.567788,0.133301,0.804406,0.021781,0.137185,0.003390,0.787441,0.006931,0.002591
4,3/10/2020 3:37,47.360409,7.994212,0.928223,0.330147,0.034815,0.009020,0.246533,0.059976,0.076961,0.001761

In [ ]:
import reverse_geocoder as rg

loc = list()
coor = list()
for i in range(len(data)):
    coor.append((data.iloc[i, 1],  data.iloc[i, 2]))

flag = 0
total = len(data)
for i in coor:
    print('\r' + '%.3f' % (flag/total*100), end = '')
    loc.append(rg.search(coor))
    flag += 1

loc[0]

0.000Loading formatted geocoded file...
8.410

In [ ]:
type(coordinates)